name: multi_split_view_example
description: A multi split view example.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  multi_split_view:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true